### ISSUE TITLE
Favorites screen - Dates are not scrollable 

### ISSUE THREAD

**Issue by StefanLobbenmeier** [voxxrin/voxxrin3#104]
In this screen there is no way to look at Thursday and Friday because you cannot scroll vertically:

![image](https://github.com/user-attachments/assets/d8582df4-6d6e-43d0-980a-4bcd03a6dafd)

as a workaround you can switch to another screen, select the date there and go back to favorites, which then shows you the favorites for the day you selected on another screen

**Comment by fcamblor** [comment]
Oh yes good catch !

I guess you're rather talking about an _horizontal_ (not _vertical_) scroll in the day selector component on the top
This also applies to Feedbacks tab

On Schedule tab, we have an horizontal scrollbar which allows to switch to thursday/friday

Ping @robinlopez : would you have some time to look at this ?

**Comment by robinlopez** [comment]
The scrolling problem on the favourites screen is fixed

**Comment by fcamblor** [comment]
deployed to Prod (thanks @robinlopez 🙏)

cc @StefanLobbenmeier (you may need to wait for the service worker cache to be updated)

**Comment by StefanLobbenmeier** [comment]
Could confirm (force closing the app and restarting seems to have done the trick for me)
