### ISSUE TITLE
Show audience level

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#11]
The audience level should also be shown in the description of the talk

![image](https://github.com/voxxrin/voxxrin3/assets/179457/a2c5f96e-4457-4a92-9740-de38f367428d)

**Comment by fcamblor** [comment]
I will consider it as a tag (not every conference will have this kind of information)

Something like `Audience: Beginner`

**Comment by fcamblor** [comment]
Fixed as tag in Demo / Devoxx Demo environments
<img width="434" alt="Cursor_and_Devoxx_conferences_companion" src="https://github.com/voxxrin/voxxrin3/assets/603815/d2e6409c-c8ca-40a3-9751-3f056ef7c4ce">
