### ISSUE TITLE
Search with no results shows nothing

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#14]
When i search on something with no results, the page shows nothing.

Instead it should show : "No search results for xxxx" 

![image](https://github.com/voxxrin/voxxrin3/assets/179457/cacf5386-489f-4656-8563-49cb37482c1a)

**Comment by fcamblor** [comment]
FYI, as a first step, I added an explicit "No talks found for selected day"

That being said, @robinlopez made a UI proposal to give matching results on other days like this : 
![image](https://github.com/voxxrin/voxxrin3/assets/603815/c006e7af-2bcb-4d34-935f-538b1598acba)

 Not sure if we will have the time to integrate this for next week, we'll try our best.

**Comment by fcamblor** [comment]
closing this one, as multi-day search should be handled on #17
