### ISSUE TITLE
Popup title should say "Install Devoxx App"

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#16]
![mobile-msg](https://github.com/voxxrin/voxxrin3/assets/179457/5a06791a-7503-4fef-8cc7-23895a3d325e)

**Comment by fcamblor** [comment]
Closing as I assume you've got a cache issue (icon has changed, as has the app title)
![image](https://github.com/voxxrin/voxxrin3/assets/603815/663cfabf-6624-415f-ae4d-b8e1f849cc59)
