### ISSUE TITLE
Clicking a talk doesn't give me the details page

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#25]
<img width="746" alt="Screenshot 2023-08-28 at 13 05 45" src="https://github.com/voxxrin/voxxrin3/assets/179457/d82b1a88-cf83-4115-b8ce-930026002e0c">

**Comment by stephanj** [comment]
It seems this is related to the IFRAME.

This is what ChatGPT has to say about it...  
<img width="746" alt="image" src="https://github.com/voxxrin/voxxrin3/assets/179457/bb24d558-51b5-4853-845a-a4a117c632a0">

**Comment by fcamblor** [comment]
@stephanj not sure to find the embedded schedule from Devoxx BE, willing to share an URL to reproduce ?

**Comment by fcamblor** [comment]
Closing (@stephanj don't hesitate to re-open it if you feel there should be some area of improvement for better integration on the devoxx website)
