### ISSUE TITLE
"Add Feedback" shows 12 Votes

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#29]
The Feedback page shows by default "12 Votes" for each possible feedback, this should be 0.

<img width="1897" alt="image" src="https://github.com/voxxrin/voxxrin3/assets/179457/aca169a0-f450-42ab-bf65-43560313f397">

**Comment by fcamblor** [comment]
Yes this is currently hardcoded in order to showcase openfeedback-like implementation.

I will revert to a standard list of items (without showing number of votes) until I implement #23

**Comment by fcamblor** [comment]
Reverted to previous design for bingo in prod/demo : 
<img width="511" alt="Devoxx_conferences_companion" src="https://github.com/voxxrin/voxxrin3/assets/603815/2869b259-dbff-4762-a354-a65214f6dc38">

PS: is it normal to have duplicated bingo entries ?
(see "Difficult to understand" with ids 1 and 6: https://gist.github.com/stephanj/7d91c0273c16580bd1ef106d0a8097e6/#file-dvbe-json-L34)

**Comment by stephanj** [comment]
Removed the duplicates.  Thanks!
