### ISSUE TITLE
Only allow "Ratings" and "Feedback" once the talk has started

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#30]
A user should only be allowed to rate a talk or give feedback, when the talk has started NOT BEFORE.

**Comment by fcamblor** [comment]
That's the expectation, can you point me to an example where it isn't ?

**Comment by stephanj** [comment]
Here are the steps to rate and submit feedback:

Step 1
<img width="858" alt="Screenshot 2023-09-01 at 09 59 54" src="https://github.com/voxxrin/voxxrin3/assets/179457/9279e0ca-c46e-40de-ae81-b6f7dd383cf6">
Step 2 
<img width="1169" alt="Screenshot 2023-09-01 at 10 00 09" src="https://github.com/voxxrin/voxxrin3/assets/179457/19998a41-86fd-42ae-855a-c7842fba7dd6">
Step 3
<img width="1169" alt="Screenshot 2023-09-01 at 10 00 20" src="https://github.com/voxxrin/voxxrin3/assets/179457/9e2dd70a-dde9-4047-83e0-a59d32ea9ce3">

**Comment by fcamblor** [comment]
OK, I missed checking for "past" timeslot on Feedback Pages.

Deployed a fix on both Prod & Demo envs.
