### ISSUE TITLE
Talk details page is empty when offline

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#31]
When viewing the schedule offline, the talk details page is empty when you click on a talk you've not yet loaded.
Would be better if a message was shown instead.

![image](https://github.com/voxxrin/voxxrin3/assets/179457/a6883c19-d189-4575-9544-7c0dab696682)

**Comment by fcamblor** [comment]
This surprises me because, as state in #32, talk details are supposed to be pre-cached after 5s : 
https://github.com/voxxrin/voxxrin3/blob/main/mobile/src/state/useSchedule.ts#L100

Let's discuss on #32 about the whole offline thing, will close this issue to avoid dispersion.
