### ISSUE TITLE
Offline viewing schedule

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#32]
It seems the schedule is cached per day, so if you viewed for example day 3 of a 5 days event.  The other days will not show anything.  Is it not possible to load all days of the event when online, so these are all cached? 

Another option could be an like Google maps does:  "Load event for offline viewing".
This would load the full schedule and talk details in one go!

**Comment by fcamblor** [comment]
Version deployed recently this week is far better regarding offline support
=> closing the issue (don't hesitate to reopen it if you still find issues)
