### ISSUE TITLE
Please add day + date to presentation details "header"

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#33]
<img width="419" alt="image" src="https://github.com/voxxrin/voxxrin3/assets/179457/9f43e30c-dc38-419b-bfbf-683e38b33a06">

**Comment by fcamblor** [comment]
fix deployed to prod & demo
<img width="404" alt="Voxxrin_-_Your_conference_companion" src="https://github.com/voxxrin/voxxrin3/assets/603815/232d2610-8616-4bbe-af59-102fcbff55d3">
