### ISSUE TITLE
Introduce eTag for the talkFeedbacksViewers request

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#35]
Would be nice to also have eTags support for the talkFeedbacksViewers request.

**Comment by fcamblor** [comment]
Not sure if this is relevant, as this endpoint is not supposed to change frequently (it may return different values only if some talks are added during crawling)

=> For me, this API should be called only once for all per event

**Comment by stephanj** [comment]
These sponsor talks are really only added in the last couple of weeks before the event starts, because we only get that info last-minute.  As a result your list of talkId registrationURL's will need updating.

**Comment by fcamblor** [comment]
ok, noted, I need to keep track of latest talk creation/deletion dates then, in order to take it into consideration for the ETag generation.

**Comment by fcamblor** [comment]
Implemented ETag support and deployed it in PROD+DEMO environments
