### ISSUE TITLE
Make it clear about what we can do with user preferences button

### ISSUE THREAD

**Issue by fcamblor** [voxxrin/voxxrin3#46]
Currently in production, we're showing user profile button, but with no possibility to click it

This makes it misleading, and we have user feedbacks wondering how we can authenticate when they see it.

We should make clearer: 
- Either don't provide user preferences screen access and, if that's the case, hide the button completely (on every screens)
- Or make it clickable, meaning that : 
   - We should review what buttons are implemented (or not) on user preferences screen
   - We should make it clear that no personal data is tracked at any moment at the moment from the app
   - Authentication will come in the future, but not available at the moment

**Comment by robinlopez** [comment]
@fcamblor I prepared the style for a component used to broadcast computerized messages. 

<img width="389" alt="Capture d’écran, le 2023-09-28 à 10 01 32" src="https://github.com/voxxrin/voxxrin3/assets/5637988/d643205f-e6c4-492e-aabd-4b8d98b8e582">

**What remains to be done:** 
Transform this model into a component by making the values (title / text / icon / type (4 possible types)) "dynamic".
