### ISSUE TITLE
UI bug during progress

### ISSUE THREAD

**Issue by fcamblor** [voxxrin/voxxrin3#52]
Hour overlaps progress bar on some configurations :
![image](https://github.com/voxxrin/voxxrin3/assets/603815/23c04f9e-2c1e-4046-a5b5-a67eaff142e7)

**Comment by fcamblor** [comment]
@robinlopez if you can look at this one maybe ?

**Comment by robinlopez** [comment]
@fcamblor Fix branche "develop"

**Comment by fcamblor** [comment]
deployed to prod yesterday
