### ISSUE TITLE
Change illu for "no results" on schedule page

### ISSUE THREAD

**Issue by fcamblor** [voxxrin/voxxrin3#68]
The illustration used for "no results" on schedule page is the same than the one on event selector (home) page.

It would be nice if we could have an illustration which is closer to the schedule page.
<img width="460" alt="Voxxrin_-_Your_conference_companion" src="https://github.com/voxxrin/voxxrin3/assets/603815/d98df78b-aea0-45b9-b83e-1b74474f430b">

**Comment by robinlopez** [comment]
Push branche "develop"
