### ISSUE TITLE
Consider fixing iOS tab navigation bugs

### ISSUE THREAD

**Issue by fcamblor** [voxxrin/voxxrin3#75]
It looks like we (still) have navigation bugs, particularly with Back button on iOS from Schedule page.

Given the complexity of ionic navigation AND the fact that this topic leads to regression, I would encourage to write e2e tests to ensure navigation is well handled, including on every native (android/ios) platforms
(not sure if writing tests and executing them into a native environment through automation is easy, but that's definitely something we should consider at some point...)

**Comment by StefanLobbenmeier** [comment]
It seems the Tab Navigation does not replace the active screen but pushes an additional screen onto the stack which gives you unexpected behavior

**Comment by fcamblor** [comment]
@StefanLobbenmeier I think you're definitely right 👍 (you're on iOS, correct ?)
This behaviour seems to only happen on iOS and not on Android

**Comment by fcamblor** [comment]
fixed

It looks like `ionRouter.back()` had to be called in a deferred way when coupled with `router.go(-x)` on iOS
