### ISSUE TITLE
Improving Lighthouse's Accessibility & SEO scores

### ISSUE THREAD

**Issue by fcamblor** [voxxrin/voxxrin3#78]
@robinlopez I ran a lighthouse report on prod, and we should improve (I think) a lot our score quickly : 
- `button`[not having accessible names](https://dequeuniversity.com/rules/axe/4.8/button-name)
- `alt` tags [on pictures](https://dequeuniversity.com/rules/axe/4.8/image-alt)
- on schedule, problems on `[role]` tag [where some children definitions are missing](https://dequeuniversity.com/rules/axe/4.8/aria-required-children) + the opposite [on child => parent relationships](https://dequeuniversity.com/rules/axe/4.8/aria-required-parent)
- Problem on `user-scalable=no` in meta tags, [which is preventing visually impaired persons to zoom](https://dequeuniversity.com/rules/axe/4.8/meta-viewport)
- Some contrast issues (on some elements not customizables by conf organizers)

I would like to fix those issues so that it's not a problem for conferences that are placing accessibility at a high level of priority.

**Comment by robinlopez** [comment]
@fcamblor Push adjustment on the branch `78_improving-lighthouses-accessibility`

**Comment by fcamblor** [comment]
@robinlopez I merged your work on `78_improving-lighthouses-accessibility` into `develop` thanks 👍
