### ISSUE TITLE
Show an indicator corresponding to the room full capacity rate

### ISSUE THREAD

**Issue by fcamblor** [voxxrin/voxxrin3#79]
Floxx app should be able to send us realtime rooms' full capacity rate so that we can display it into voxxrin.

Impacts : 

- [x] @fcamblor Provide a dedicated endpoint for Floxx App with a dedicated token to access it
- [x] @fcamblor This endpoint will fill a dedicated (public) firestore collection `/events/{eventId}/roomsStats` having following structure : 
```
{
    "1709": { // 1709 is a room ID, DevoxxFR's Amphi Bleu here...
        "lastUpdatedOn": "2024-04-17T07:02:15Z",
        "fullCapacityRate": 1.0
    },
    "1705": {
        "lastUpdatedOn": "2024-04-18T08:28:00Z",
        "fullCapacityRate": 0.93
    }
...
}
```
- [x] @fcamblor On schedule page, we should display an indicator for upcoming rooms having a talk in it : 
    - If we didn't get any `fullCapacityRate` raised by red coats (we don't have any entry for target room OR `lastUpdatedOn` for this room is **before** previous talk's end time minus 10% of its duration OR `lastUpdatedOn` for this room is **after** target talk's end time minus 10% of its duration), we should display a small "?" indicator
    - If `fullCapacityRate` is < 0.6, we should display a **green** indicator stating there are still plenty of available seats
    - If `fullCapacityRate` is >= 0.6 and < 0.8, we should display a **yellow** indicator stating the room is becoming crowded
    - If `fullCapacityRate` is >= 0.8 and < 0.99, we should display a **red** indicator stating that only few seats are left
    - If `fullCapacityRate` is >= 0.99, we should display a **black** indicator that the room is full
 - [x] @robinlopez to provide UI for this indicator  
 - [x] @fcamblor to check if an event crawling is not going to reset room stats (we've got a strange behaviour on wed 3rd, where every room capacities were resetted)

@robinlopez If you could think about an indicator above schedule cards to show this colored information, it would be nice (given that it's only a temporary information useful only for next talks, I would not add this INSIDE the card, but maybe ON TOP of it) : 

![Voxxrin_-_Your_conference_companion](https://github.com/voxxrin/voxxrin3/assets/603815/5f705e7d-ef8b-4af8-9777-72cbef3f24be)

**Comment by fcamblor** [comment]
Here is the UI for room capacity indicators (these are only displayed for upcoming time slots)

<img width="401" alt="Cursor_and_Voxxrin" src="https://github.com/voxxrin/voxxrin3/assets/603815/73b3b204-f0d4-44bc-8d1e-e066e3df0088">

**Comment by robinlopez** [comment]
@fcamblor Design adjustment OK
![Capture d’écran, le 2024-04-05 à 15 09 55](https://github.com/voxxrin/voxxrin3/assets/5637988/593deba2-0d41-479d-a7d4-045ce011dc05)
![Capture d’écran, le 2024-04-05 à 15 10 17](https://github.com/voxxrin/voxxrin3/assets/5637988/80c1f1d9-06d3-413e-abed-db9ccdd162c5)

**Comment by fcamblor** [comment]
Great idea to have a dedicated icon for full rooms ! 😍

**Comment by fcamblor** [comment]
closing as I'll consider this as merged into develop
