### ISSUE TITLE
Show year next to date

### ISSUE THREAD

**Issue by stephanj** [voxxrin/voxxrin3#8]
Show also the year next to the date because in example the year in the title is cut-off 

![image](https://github.com/voxxrin/voxxrin3/assets/179457/1d6cb75f-3ecd-48e4-ba1d-b42f78b2fd4a)

**Comment by fcamblor** [comment]
fixed in `demo` & `devoxx-demo` environments
<img width="444" alt="Devoxx_conferences_companion" src="https://github.com/voxxrin/voxxrin3/assets/603815/239287b9-95cc-4041-8e84-f42c8cd4c148">
