### ISSUE TITLE
[Bug - Events List] Unwanted navigation problem when switching from one tab to another (Future / Past)

### ISSUE THREAD

**Issue by robinlopez** [voxxrin/voxxrin3#80]
**Case:** 
When you pass over the Past tab, scroll down to see the items in this list, scroll back up to find the tabs and then click on the Future tab again, you navigate to the first event pinner.

**Note:** 
If no scrolling is performed between tab changes, no problem.
Problem only present on mobile device (tested on Android - to be verified on IOS) 

**See video to understand the problem.**https://github.com/voxxrin/voxxrin3/assets/5637988/fc6ea6b6-c7de-44f2-ad27-a3a1fb5e2a56

**Comment by robinlopez** [comment]
@fcamblor Fix push branche `80_fix-bug-scroll-event-selector`

**Comment by fcamblor** [comment]
I'm not sure to properly understand what are [the implications behind `scrollable` direction on `ion-segment`](https://ionicframework.com/docs/api/segment#scrollable-segments)

Closing as I merged the branch on develop... let's check if this really never happen again afterward.
